# Generated by Django 4.0.1 on 2022-03-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EPSP_Djanet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Morning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mornings_of_worker', to='EPSP_Djanet_app.healthworkers')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mornings_of_service', to='EPSP_Djanet_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='healthworkers',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_workers', to='EPSP_Djanet_app.service'),
        ),
        migrations.CreateModel(
            name='Garde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('health_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes_of_worker', to='EPSP_Djanet_app.healthworkers')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardes_of_service', to='EPSP_Djanet_app.service')),
            ],
        ),
    ]
